defaults:
  - analyze_latent_schema

batch_size: 10

reducer:
  _target_: sklearn.manifold.TSNE
  # _target_: umap.UMAP

model:
  categorical_weights: ${weights:${data.categorical_inputs}}
  continuous_weights: ${weights:${data.continuous_inputs}}
  num_hidden:
    - 1000
  num_latent: 150
  beta: 0.0001
  dropout: 0.1
  cuda: false

training_loop:
  lr: 1e-4
  num_epochs: 40
  batch_dilation_steps:
    - 50
    - 100
    - 150
  kld_warmup_steps:
    - 80
    - 82
    - 84
    - 86
    - 88
    - 90
    - 92
    - 94
    - 96
    - 98
    - 100
    - 102
    - 104
    - 106
    - 108
    - 110
    - 112
    - 114
    - 116
    - 118
    - 120
    - 122
    - 124
    - 126
    - 128
    - 130
    - 132
    - 134
    - 136
    - 138
    - 140
    - 142
    - 144
    - 146
    - 148
    - 150
  early_stopping: false
  patience: 0
