defaults:
  - analyze_latent

batch_size: 10

feature_names:
  - drugs_20
  - metagenomics_174
  - proteomics_195

model:
  num_hidden:
    - 1000
  num_latent: 3

training_loop:
  lr: 1e-4
  num_epochs: 12
  # num_latent: 3
  # beta: 0.001
# maybe Ineed to add the bet aand the num_latent
